### ISSUE TITLE
unix path names

### ISSUE THREAD

**Issue by UlrichBerntien** [ivoprogram/overwrite-testing#2]
The characters ':' and '\' have special functions in Windows file system. But in Unix file systems this are "normal" characters.
Overwrite handles path names with ':' and '' at the end not correct. A workaround is possible: call overwrite with '/' at the end of the path name.
':' at the end causes only an error message. '\' at the end causes file creation in the wrong directory.

**Comment by ivoprogram** [comment]
This has already been fixed in version 1.4.1 2019-11-03.
There is no character : left at the end, the program add /
But I will check again for all and test it in unix for " issue.
Thank you.

**Comment by ivoprogram** [comment]
Fixed this issues in Version 1.4.2 2019-11-07.
I have also added test and results in this repo.

Unicode in path is not supported in command line overwrite.c for now, shoud be in next releases.
Changed FILE_PREFIX and set to empty, no reason to write long file names, entries are allocated any way should be used -dirs:n 

See following links for FAT long file names, the reason for FILE_SUFFIX
https://en.wikipedia.org/wiki/Long_filename#Limits
https://web.archive.org/web/20061018063912/http://www.cocoadev.com/index.pl?MSDOSFileSystem

**Comment by ivoprogram** [comment]
> 03_test_unix_names.log:
> Space as first character in a path name is possible in Unix and also in Windows file systems.
> 

I don't consider this as issue, in a case of space at first character in path the user can use another directory,  anyway this is not common case.

> 04_ext4_file_names.log:
> 5 test files with long names and "overwrite -dirs:1000 -data:all" does not overwrite all parts of the file names.

The new version 1.5 2019-11-09 now overwrite also long file names with less meta entries, I have added long suffix to written entries.
I don't consider this as issue, the overwrite program is intended for common use 99% of cases, it not cover all the possible cases, in cases like this of file name with more than 200 characters if not overwritten the user can search other solutions than overwrite program.

**Comment by ivoprogram** [comment]
This tests fail because the tests are not good, and not the overwrite program.

I have created test scripts with different file systems that demonstrate that the overwrite program clean also metadata, demonstration on FAT, EXT2, EXT3, EXT3 also with long file names.
https://github.com/ivoprogram/overwrite-testing/tree/master/ivoprogram/02


> 01_test_short_names.sh

Fail because at line 28 only one file is deleted and not also the second file, overwrite program does not overwrite existing files, only deleted.

> 02_test_overflow.sh

Fail because the script pass more than 1000 chars in path as one file name not as path with separators,
Linux has limits file name 255, path 4096.

> 03_test_unix_names

I have answered to this in issues #2. 
I don't consider this as issue, in a case of space at first character in path the user can use another directory, anyway this is not common case.
The overwrite program is intended for common use 99% of cases, it not cover all the possible cases, otherwise the user can search other solutions than overwrite program.

> 04_ext4_file_names.log:
> 5 test files with long names and "overwrite -dirs:1000 -data:all" does not overwrite all parts of the file names.

This test fail because ext3 and ext4 have journal, so the script find remainig data in journal not in file system metadata structure.
The solution is to disable journaling overwrite and enable journaling, i have created test scripts that demonstrate this.

**Comment by ivoprogram** [comment]
Check the new version 1.5.1 2019-11-14, now it pass tests. 
https://github.com/ivoprogram/overwrite-testing/tree/master/ivoprogram/03

**Comment by ivoprogram** [comment]
Check the new Version 1.5.2 2019-11-16, fixed last issues, pass my tests for upper and long file names.
https://github.com/ivoprogram/overwrite-testing/tree/master/ivoprogram/04

**Comment by UlrichBerntien** [comment]
The new overwrite version 1.5.2 passes all the test cases.
