### ISSUE TITLE
meaning of "-data" parameter?

### ISSUE THREAD

**Issue by bsto** [ivoprogram/overwrite-testing#8]
I tried out Overwrite on my Windows 7 system and a 1 TB NTFS hard disk partition.

When I enter

overwrite.exe -test -rand -path:d:\

it lasts ~1 ms.

I cannot imagine that it is so fast.

I guess a -data parameter is missing. But what is the meaning?
Users can specify

-data:all

But shouldn't it be always "all"?
It doesn't make sense to wipe only the (first?) 10MB of free space of a partition.

Moreover what means "Metadata"?
Metadata of what?
MFT of partition?

I am confused. Maybe someone can help
Ben

**Comment by ivoprogram** [comment]
Hello

There is more info for overwrite program on following link, check also the reference links on that page you will find all info that you need: 
https://ivoprogram.github.io/?content=overwrite.html

> I guess a -data parameter is missing

Yes -data or -meta parameters has to be entered.

> But what is the meaning?

Parameter -data means how much quantity of data on disk has to be overwritten.

> But shouldn't it be always "all"?
> It doesn't make sense to wipe only the (first?) 10MB of free space of a partition.

Data should specify quantity of data to overwrite, all (all empty space), 1mb (1 megabyte), 1gb (1 gigabyte).
It make sense to wipe only first megabytes of data on partition because it will clean the remaining data of deleted files, based on allocations alghoritms operating system allocate first available space for data and metadata.

> Moreover what means "Metadata"?
> Metadata of what?
> MFT of partition?

Metadata of files and directories, as name, size, date, yes MFT of partition.

> I am confused. Maybe someone can help

Overwrite program is still in development, there will be more documentation.
I would reccomend to see the book: 
File System Forensic Analysis by Brian Carrier 
https://www.oreilly.com/library/view/file-system-forensic/0321268172/

**Comment by ivoprogram** [comment]
Fixed the issue for -data parameter check if missing, check the new version 1.5.2 2019-11-16.
https://github.com/ivoprogram/overwrite/tree/master/c

**Comment by ivoprogram** [comment]
This issue has been resolved, closing.
